apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: aws-dynamodb
  namespace: istio-system  # Single entry in istio-system for cluster-wide access
spec:
  hosts:
    - dynamodb.us-east-2.amazonaws.com
  ports:
    - number: 443
      name: https
      protocol: TLS
  location: MESH_EXTERNAL
  resolution: DNS