namespace: purchasing-supply-optimization

resources:
  # Order here is important
  - kafka.yaml
  - routes.yaml
  - suppliers.yaml
  - contracts.yaml
  - purchase-plans.yaml
  - ../common/aws-credentials