apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-suppliers
  namespace: purchasing-supply-optimization
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: default
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: purchasing-supply-optimization-route
  namespace: purchasing-supply-optimization
spec:
  parentRefs:
    - name: medisupply-gateway
      namespace: default
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/suppliers
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: suppliers
          port: 8080
