apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: purchases-rabbitmq-source
  namespace: financial-billing
spec:
  rabbitmqClusterReference:
    # Using the in-cluster RabbitMQ defined in financial-billing namespace
    name: financial-billing-rabbitmq
  rabbitmqResourcesConfig:
    parallelism: 10
    exchangeName: "purchases.exchange"
    queueName: "purchases.events"
  delivery:
    retry: 5
    backoffPolicy: "linear"
    backoffDelay: "PT1S"
#  sink:
#    ref:
#      apiVersion: serving.knative.dev/v1
#      kind: Service
#      name: event-display
#      namespace: default