# commerce-sales/postgres/pg-auth.secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pg-auth
  namespace: commerce-sales
type: Opaque
stringData:
  postgres-password: "admin"        # superuser 'postgres'
  password: "admin"                 # password for 'app_user'
  replication-password: "admin-repl"
  username: "app_user"              # <— ADD / FIX
  database: "salesdb"               # <— ADD / FIX
