##################################################################################################
# trips service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: trips
  labels:
    app: trips
    service: trips
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: trips
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: medisupply-trips
  labels:
    account: trips
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-v1
  labels:
    app: trips
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
      version: v1
  template:
    metadata:
      labels:
        app: trips
        version: v1
    spec:
      serviceAccountName: medisupply-trips

      containers:
        - name: trips
          image: public.ecr.aws/q2b4w2e6/dummies/ruta-ms:1.3.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE_NAME
              value: "RUTA MS"
            # Use FQDN for cross-namespace communication
            - name: NORMATIVA_MS_URL
              value: "http://regulations.regulatory-health-compliance.svc.cluster.local:3000"
            - name: VEHICULO_MS_URL
              value: "http://vehicles.logistics-distributions.svc.cluster.local:3000"
            - name: AWS_ENDPOINT_URL_DYNAMODB
              value: "https://dynamodb.us-east-2.amazonaws.com"
            - name: AWS_ACCESS_KEY_ID
              valueFrom: { secretKeyRef: { name: aws-credentials, key: AWS_ACCESS_KEY_ID } }
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom: { secretKeyRef: { name: aws-credentials, key: AWS_SECRET_ACCESS_KEY } }
            - name: AWS_REGION
              valueFrom: { secretKeyRef: { name: aws-credentials, key: AWS_REGION } }
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10