##################################################################################################
# vehicles service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: vehicles
  labels:
    app: vehicles
    service: vehicles
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: vehicles
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: medisupply-vehicles
  labels:
    account: vehicles
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicles-v1
  labels:
    app: vehicles
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicles
      version: v1
  template:
    metadata:
      labels:
        app: vehicles
        version: v1
    spec:
      serviceAccountName: medisupply-vehicles

      containers:
        - name: vehicles
          image: public.ecr.aws/q2b4w2e6/dummies/vehiculo-ms:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: SERVICE_NAME
              value: "VEHICULO MS"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10