##################################################################################################
# batches service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: contracts-service
  labels:
    app: contracts-service
    service: contracts-service
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: contracts-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: medisupply-contracts-service
  labels:
    account: contracts-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contracts-service-v1
  labels:
    app: contracts-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contracts-service
      version: v1
  template:
    metadata:
      labels:
        app: contracts-service
        version: v1
    spec:
      serviceAccountName: medisupply-contracts-service

      containers:
#      - name: contracts-service
#        image: public.ecr.aws/a7x9j8u1/medisupply/procurement-supply-optimization/contracts-web-service:latest
#        imagePullPolicy: Always
#        ports:
#        - containerPort: 3000
#        env:
#          - name: SERVICE_NAME
#            value: "Contracts Service"
#          - name: KAFKA_BROKERS
#            value: "my-cluster-kafka-bootstrap.procurement-supply-optimization.svc.cluster.local:9092"
#          - name: KAFKA_CLIENT_ID
#            value: "contracts-service"
#          - name: PORT
#            value: "3000"
#        resources:
#          requests:
#            memory: "128Mi"
#            cpu: "100m"
#          limits:
#            memory: "256Mi"
#            cpu: "200m"
#        readinessProbe:
#          httpGet:
#            path: /health
#            port: 3000
#          initialDelaySeconds: 2
#          periodSeconds: 5
#        livenessProbe:
#          httpGet:
#            path: /health
#            port: 3000
#          initialDelaySeconds: 5
#          periodSeconds: 10
      - name: contracts-worker
        image: public.ecr.aws/a7x9j8u1/medisupply/procurement-supply-optimization/contracts-worker-service:latest
        imagePullPolicy: Always
        env:
          - name: SERVICE_NAME
            value: "CONTRACTS-MS-WORKER"
          - name: KAFKA_BROKERS
            value: "my-cluster-kafka-bootstrap.procurement-supply-optimization.svc.cluster.local:9092"
          - name: KAFKA_CLIENT_ID
            value: "contracts-ms-worker"
          - name: KAFKA_GROUP_ID
            value: "contracts-workers"
          - name: KAFKA_TOPICS
            value: "medicine.events"
          - name: DDB_TABLE
            value: "contracts-db"
          - name: AWS_REGION
            value: "us-east-2"
          - name: KAFKA_DEFAULT_PARTITIONS
            value: "1"
          - name: KAFKA_DEFAULT_REPLICATION_FACTOR
            value: "1"
