##################################################################################################
# sales service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: sales
  labels:
    app: sales
    service: sales
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: sales
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: medisupply-sales
  labels:
    account: sales
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-v1
  labels:
    app: sales
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sales
      version: v1
  template:
    metadata:
      labels:
        app: sales
        version: v1
    spec:
      serviceAccountName: medisupply-sales
      containers:
      - name: sales
        image: public.ecr.aws/q2b4w2e6/dummies/venta-ms:1.3.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
          - name: SERVICE_NAME
            value: "VENTA MS"
          # Use FQDN for cross-namespace communication
          - name: CENTRO_MS_URL
            value: "http://distribution-centers.inventories-storage.svc.cluster.local:3000"
          - name: RUTA_MS_URL
            value: "http://trips.logistics-distributions.svc.cluster.local:3000"
          #- name: AWS_ENDPOINT_URL_DYNAMODB
  #          value: "https://dynamodb.us-east-2.amazonaws.com"
          - name: AWS_ACCESS_KEY_ID
            valueFrom: { secretKeyRef: { name: aws-credentials, key: AWS_ACCESS_KEY_ID } }
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom: { secretKeyRef: { name: aws-credentials, key: AWS_SECRET_ACCESS_KEY } }
          - name: AWS_REGION
            valueFrom: { secretKeyRef: { name: aws-credentials, key: AWS_REGION } }
        readinessProbe:
          httpGet: { path: /health, port: 3000 }
          initialDelaySeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /health, port: 3000 }
          initialDelaySeconds: 5
          periodSeconds: 10