apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: purchase-trigger
  namespace: medisupply-eventing
spec:
  broker: medisupply-broker
  filter:
    attributes:
      type: updated.med
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: purchases #service name

