apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: purchase-trigger
  namespace: medisupply-eventing
spec:
  broker: medisupply-broker
  filter:
    attributes:
      type: medicine.updated
  subscriber:
    uri: http://purchases.financial-billing.svc.cluster.local:8080

