apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sales-trigger
spec:
  broker: medisupply-broker
  filter:
    attributes:
      type: medicine.updated
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: sales #service name

